### ISSUE TITLE
Refresh ads quickly causes problems with postscribe.

### ISSUE THREAD

**Issue by dbrans** [krux/postscribe#13]
@adrienbataille wrote:

Derek,
You can see here my jsfiddle with a snippet which looks like my code

http://jsfiddle.net/qXJ4j/3/

To reproduce the bug on jsfiddle, you have to quickly click many times on the link, and "done" is not called after.
But on my website, the error occurs both on loading the page and after requests to get content with all new advertising links (got with postscribe). On each page, postcribe is used at list 4 times at same time.
My browsers are Chrome and Safari on Mac OS.
Adrien

**Comment by EnricoKestenholz** [comment]
I had the same problem with an html5 mobile application.

Every new page the ads are called, and everything works fine with normal uses, but in cases where the user changes pages quickly this error occurs frequently enoguh.
 
All the banners are called after the new page has been loaded (so that the banner positions exist before calling postscribe), this way the user has a "window" that it can change page and brake postscribe.

Being an HTML5 app the "new page" is not an actual new page, but it's the dom being rewritten and there isn't an easy way form me to empty the banners before every new page call.

The error is on the insertScript function on line 544
    cursor.parentNode.replaceChild(el, cursor);

This because the cursor is null when it's called.

My main problem (being an HTML5 app) is that if this error occurs the active var doesn't clear and all the ads after the error just get qued up. 

I wasn't able to handle the error, or clear postscribe directly only *if* the error occurred. 

So what I did was a bit more drastic, I've added a check if the cursor exist before calling the insertscript
     
     if(cursor){
          cursor.parentNode.replaceChild(el, cursor);
     }
    
And I've added an option "clear" on the postscribe call

      if (isFunction(options)) {
                options = {
                    done: options
                };
      }else if(options == "clear") {
                queue = [];
                active = null;
                nextId = 0;
                return;
       }

This way, on every page change, before calling the ads i clear postscribe with a call to `postscribe(null, "", "clear")`

It will still give the error, so it's not really a fix, but this way it won't stop postscribe working on the next page.

**Comment by jozye** [comment]
Hi, 

I just wanted to get an idea of whether a supported fix is coming for this please? 

I currently have a client using this on an Angular JS based site and they are reporting issues with fast page changes which ultimately impacts on any paid media once postscribe breaks. 

We appreciate that some workarounds have been given by user's for this but are uncertain of how sustainable they are for this site. 

We really like postscribe and love what it's doing to help us, but just wanted to check on this sticking point before we spend time applying a workaround for this. 

Thanks!

**Comment by jnewman** [comment]
Hello @jozye I'm buried right now. I don't think I'll be able to work on a patch in the near future.

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
