### ISSUE TITLE
Problem capturing in some cases

### ISSUE THREAD

**Issue by jaysee** [krux/postscribe#95]
Hello,

(test using FF 34)
I've got a strange behavior :
http://jsfiddle.net/8g838dyq/4/

this seems to catched the first classic document.write call

this should have output
```
POSTCRIBE call : Foo
Direct Call 2 : Foo
Direct Call 3 : Foo
Direct Write : foodirect 
```

if there is a previous document.write, there seems to be OK
http://jsfiddle.net/8g838dyq/

but if a use the same code, but another external JS (that does almost the same thing), it does not works anymore
http://jsfiddle.net/8g838dyq/2/

theses ones are also stranges :
http://jsfiddle.net/8g838dyq/1/
http://jsfiddle.net/8g838dyq/3/

so i don't understand how to use postscribe ? or something ?

Is postscribe able to only catch the document.write of the html we send to him or does it catches all document.write of the page ?

**Comment by jnewman** [comment]
A mix and match isn't going to work. To get around this you can schedule the postscribe writes to happen after onload. Because document.write doesn't work after onload you can't run into a valid conflict. 

For example w/ jQuery: http://jsfiddle.net/wpbjf3kq/ (doesn't work for me due to mime-type errors).

**Comment by jaysee** [comment]
Thanks for the answer, good to know, i will do it this way for now!

jC
